<a href="https://colab.research.google.com/github/tral909/DL-2021/blob/main/numpy_and_linalg_hw6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 6. Домашнее задание. Numpy и линейная алгебра

### 6.1 Перемножение матриц
Напишите две функции, каждая из которых перемножает две квадратные матрицы: одна без использования встроенных функций `numpy`, а другая --- с помощью `numpy`. На вход первой задаче подаются списки размера size по size элементов в каждом. На вход второй задаче подаются объекты типа `np.ndarray` --- квадратные матрицы одинакового размера. 

Первая функция должна возвращать список списков, а вторая -- `np.array`.

In [1]:
import numpy as np

def no_numpy_mult(first, second):
    size = len(first)
    result = [[0 for k in range(size)] for m in range(size)]
    for i in range(size):
      for j in range(size):
        sum = 0
        for d in range(size):
          sum += first[j][d] * second[d][i]
        result[j][i] = sum
    return result

def numpy_mult(first, second):
    return first.dot(second)

a = [[1, 2, 3],
     [2, 3, 4],
     [3, 4, 5]]
b = [[3, 4, 5],
     [4, 5, 6],
     [5, 6, 7]]
print(no_numpy_mult(a, b))
print(numpy_mult(np.array(a), np.array(b)))

[[26, 32, 38], [38, 47, 56], [50, 62, 74]]
[[26 32 38]
 [38 47 56]
 [50 62 74]]


### 6.2 Скалярное произведение векторов
Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Реализуйте их скалярное произведение с помощью `numpy` и без. 

In [3]:
import numpy as np
from functools import reduce
from operator import add

def no_numpy_scalar(v1, v2):
    return reduce(add, map(lambda v: v[0] * v[1], zip(v1, v2)))

def numpy_scalar(v1, v2):
    return v1.dot(v2)

v1 = [1, 2, 3]
v2 = [2, 3, 4]
print(no_numpy_scalar(v1, v2))
print(numpy_scalar(np.array(v1), np.array(v2)))

20
20
