<a href="https://colab.research.google.com/github/tral909/DL-2021/blob/main/numpy_and_linalg_hw6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 6. Домашнее задание. Numpy и линейная алгебра
## 6.1 Перемножение матриц
Напишите две функции, каждая из которых перемножает две квадратные матрицы: одна без использования встроенных функций `numpy`, а другая --- с помощью `numpy`. На вход первой задаче подаются списки размера size по size элементов в каждом. На вход второй задаче подаются объекты типа `np.ndarray` --- квадратные матрицы одинакового размера. 

Первая функция должна возвращать список списков, а вторая -- `np.array`.

In [6]:
import numpy as np

def no_numpy_mult(first, second):
    size = len(first)
    result = [[0 for k in range(size)] for m in range(size)]
    for i in range(size):
      for j in range(size):
        sum = 0
        for d in range(size):
          sum += first[j][d] * second[d][i]
        result[j][i] = sum
    return result

def numpy_mult(first, second):
    return first.dot(second)

a = [[1, 2, 3],
     [2, 3, 4],
     [3, 4, 5]]
b = [[3, 4, 5],
     [4, 5, 6],
     [5, 6, 7]]
print(no_numpy_mult(a, b))
print(numpy_mult(np.array(a), np.array(b)))

[[26, 32, 38], [38, 47, 56], [50, 62, 74]]
[[26 32 38]
 [38 47 56]
 [50 62 74]]
